WITH RECURSIVE GENERATION_TABLE AS (
    SELECT      ID, 1 AS GENERATION
    FROM        ECOLI_DATA
    WHERE       PARENT_ID IS NULL
    
    UNION ALL 
    
    SELECT      e.ID, GENERATION + 1
    FROM        ECOLI_DATA e JOIN GENERATION_TABLE g ON e.PARENT_ID = g.ID
)


SELECT      e.ID
FROM        ECOLI_DATA e JOIN GENERATION_TABLE g ON e.ID = g.ID
WHERE       GENERATION = 3
ORDER BY    e.ID
