SELECT      prod.PRODUCT_CODE, prod.PRICE * SUM(sale.SALES_AMOUNT) AS SALES
FROM        PRODUCT prod JOIN OFFLINE_SALE sale ON prod.PRODUCT_ID = sale.PRODUCT_ID
GROUP BY    prod.PRODUCT_CODE
ORDER BY    SALES DESC, prod.PRODUCT_CODE