WITH rank_table AS (
    SELECT      ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS r
    FROM        ECOLI_DATA
)



SELECT  ID, (
CASE
    WHEN r / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.25 THEN 'CRITICAL'
    WHEN r / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.50 THEN 'HIGH'
    WHEN r / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END
) AS COLONY_NAME
FROM    rank_table
ORDER BY    ID