SELECT      YEAR(SALES_DATE) AS 'YEAR', MONTH(SALES_DATE) AS 'MONTH', GENDER, COUNT(DISTINCT sale.USER_ID)
FROM        ONLINE_SALE sale JOIN USER_INFO user ON sale.USER_ID = user.USER_ID
WHERE       NOT user.GENDER IS NULL
GROUP BY    YEAR, MONTH, GENDER
ORDER BY    YEAR, MONTH, GENDER