WITH RECURSIVE GENERATION_TABLE(ID, GENERATION) AS (
    SELECT      ID, 1 AS GENERATION
    FROM        ECOLI_DATA
    WHERE       PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT      d.ID, GENERATION + 1
    FROM        ECOLI_DATA d JOIN GENERATION_TABLE t ON d.PARENT_ID = t.ID
)


SELECT      COUNT(*) AS COUNT, GENERATION
FROM        ECOLI_DATA d JOIN GENERATION_TABLE g ON d.ID = g.ID
WHERE       NOT EXISTS (
    SELECT      *
    FROM        ECOLI_DATA td
    WHERE       td.PARENT_ID = d.ID
)
GROUP BY    GENERATION
ORDER BY    GENERATION