

# SELECT      HISTORY_ID, 
# ROUND(
#     ((DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE) * 
#     (CASE
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN 0.95
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89  THEN 0.93
#         WHEN 90 <= DATEDIFF(END_DATE, START_DATE) + 1 THEN 0.90
#         ELSE 1.0
#     END)
# )  AS FEE,
# FROM        CAR_RENTAL_COMPANY_RENTAL_HISTORY history JOIN CAR_RENTAL_COMPANY_CAR car ON history.CAR_ID = car.CAR_ID
# WHERE       car.CAR_TYPE = '트럭'
# ORDER BY    FEE DESC, HISTORY_ID DESC

SELECT      HISTORY_ID, ROUND(DAILY_FEE * DAYS *(100 - IFNULL(DISCOUNT_RATE, 0)) / 100) AS FEE
FROM (
    SELECT history.HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DAYS, DAILY_FEE, 
    (CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89  THEN '30일 이상'
        WHEN 90 <= DATEDIFF(END_DATE, START_DATE) + 1 THEN '90일 이상'
        ELSE NULL
    END) AS PLAN
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY history JOIN CAR_RENTAL_COMPANY_CAR car ON history.CAR_ID = car.CAR_ID
    WHERE       car.CAR_TYPE = '트럭'
) AS WITH_PLAN LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON WITH_PLAN.PLAN = p.DURATION_TYPE AND p.car_type = '트럭'
ORDER BY        FEE DESC, HISTORY_ID DESC
