SELECT      ID, EMAIL, FIRST_NAME, LAST_NAME
FROM        DEVELOPERS dev
WHERE       EXISTS (
    SELECT  CODE
    FROM    SKILLCODES
    WHERE   CATEGORY = 'Front End' AND CODE & dev.SKILL_CODE
)
ORDER BY    ID