SELECT      m1.MEMBER_NAME, r1.REVIEW_TEXT, DATE_FORMAT(r1.REVIEW_DATE, "%Y-%m-%d")
FROM        MEMBER_PROFILE m1 JOIN REST_REVIEW r1 ON m1.MEMBER_ID = r1.MEMBER_ID
WHERE       m1.MEMBER_ID = (
    SELECT      m2.MEMBER_ID
    FROM        MEMBER_PROFILE m2 JOIN REST_REVIEW r2 ON m2.MEMBER_ID = r2.MEMBER_ID
    GROUP BY    m2.MEMBER_ID
    ORDER BY    COUNT(*) DESC
    LIMIT 1     
)
ORDER BY    r1.REVIEW_DATE, r1.REVIEW_TEXT
