SELECT  info.ITEM_ID, info.ITEM_NAME, info.RARITY
FROM    ITEM_TREE tree JOIN ITEM_INFO info ON tree.ITEM_ID = info.ITEM_ID
WHERE   PARENT_ITEM_ID = (
    SELECT  ITEM_ID
    FROM    ITEM_INFO
    WHERE   RARITY = "RARE" AND ITEM_ID = PARENT_ITEM_ID
)
ORDER BY info.ITEM_ID DESC
