
SELECT  ANIMAL_ID, NAME
FROM    ANIMAL_INS ins
WHERE   EXISTS (
    SELECT  *
    FROM    ANIMAL_OUTS outs
    WHERE   outs.DATETIME < ins.DATETIME AND outs.ANIMAL_ID = ins.ANIMAL_ID
)
ORDER BY ins.DATETIME