SELECT      MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM        CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE       DATE("2022-08-00") <= START_DATE AND START_DATE < DATE("2022-11-00") AND 5 <= (
    SELECT  COUNT(*)
    FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE   DATE("2022-08-00") <= START_DATE AND START_DATE < DATE("2022-11-00") AND B.CAR_ID = A.CAR_ID
)
GROUP BY    MONTH, A.CAR_ID
ORDER BY    MONTH, A.CAR_ID DESC