WITH YEAR_SIZE AS (
    SELECT      YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM        ECOLI_DATA 
    GROUP BY    YEAR
)

SELECT      y.YEAR, y.MAX_SIZE - d.SIZE_OF_COLONY AS YEAR_DEV, d.ID
FROM        ECOLI_DATA d JOIN YEAR_SIZE y ON YEAR(d.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY    YEAR, YEAR_DEV