WITH FISH_TYPE_MEAN_LENGTH AS (
    SELECT      FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH, (
    CASE
        WHEN AVG(LENGTH) <= 10 THEN NULL
        ELSE AVG(LENGTH)
    END
    ) AS MEAN_LENGTH
    FROM        FISH_INFO
    GROUP BY    FISH_TYPE
)

SELECT      COUNT(*) AS FISH_COUNT, MAX(info.LENGTH) AS MAX_LENGTH, info.FISH_TYPE
FROM        FISH_INFO info JOIN FISH_TYPE_MEAN_LENGTH mean ON info.FISH_TYPE = mean.FISH_TYPE
WHERE       33 <= MEAN_LENGTH
GROUP BY    info.FISH_TYPE
ORDER BY    info.FISH_TYPE